version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "aviation/aviation-data"
      - "common/autoinstallers/rush-prettier"
      - "marine/aton-faults"
      - "marine/bridge-lock-disruptions"
      - "marine/gofrep"
      - "marine/marinecam"
      - "marine/nautical-warnings"
      - "marine/portactivity"
      - "marine/shiplight"
      - "marine/sse"
      - "marine/voyage-plan-gateway"
      - "other/aws-github-oidc"
      - "other/cloudfront"
      - "other/cloudwatch-logs-recipient"
      - "other/digitraffic-statistics"
      - "other/elasticsearch"
      - "other/es-key-figures"
      - "other/monitoring"
      - "other/opensearch-monitors"
      - "other/patchmanager"
      - "other/status"
      - "other/swagger-joiner"
      - "rail/rami"
      - "rail/rata"
      - "road/charging-network"
      - "road/counting-site"
      - "road/lam-history"
      - "road/maintenance-tracking-municipality"
      - "road/maintenance-tracking"
      - "road/open311"
      - "road/street-traffic-message"
      - "road/variable-signs"
      - "template/esm"
      - "tools/eslint-config"
      - "tools/rig"
      - "tools/toolchain"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  - package-ecosystem: "pip"
    directories:
      - "other/digitraffic-statistics/digitraffic-figures"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
