export enum AtonEnvKeys {
    SECRET_ID="SECRET_ID",
    SEND_FAULT_SNS_TOPIC_ARN = 'SEND_FAULT_SNS_TOPIC_ARN',
    CA_SECRETKEY = 'CA_SECRETKEY',
    CLIENT_CERTIFICATE_SECRETKEY = 'CLIENT_CERTIFICATE_SECRETKEY',
    PRIVATE_KEY_SECRETKEY = 'PRIVATE_KEY_SECRETKEY',
    INTEGRATIONS = 'INTEGRATIONS'
}
