#!/bin/sh
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Reorder changed package.json contents add reformatted files to staging to be committed
echo "Sort package.jsons..."
git diff --cached --name-only --diff-filter=ACM \
  | grep package.json \
  | grep -v 'digitraffic-common' \
  | while IFS= read -r pkg; do
  echo "Sorting $pkg"
  npx --yes sort-package-json "$pkg"
  git add "$pkg"
done
echo "Sort package.jsons done."

# run formatting to all files and add reformatted files to staging to be committed
FILES=$(npx --yes deno fmt 2>&1)
if [ -n "$FILES" ]; then
  CHANGES=$(echo $FILES | tail -n 1)
  echo $CHANGES
  echo "Adding (git add) formatted files"
  echo "$FILES" | sed '$d'
  echo "$FILES" | sed '$d' | xargs -I "{}" git add "{}"
  echo "Done"
fi

# Check package dependencies
node common/scripts/install-run-rush.js repo:check-dependencies || exit $?
