export enum ChargingNetworkKeys {
    OCPI_DOMAIN_URL = "OCPI_DOMAIN_URL",
    OCPI_PARTY_ID = "OCPI_PARTY_ID",
    OCPI_BUSINESS_DETAILS_NAME = "OCPI_BUSINESS_DETAILS_NAME",
    OCPI_BUSINESS_DETAILS_WEBSITE = "OCPI_BUSINESS_DETAILS_WEBSITE"
}
