ARG FUNCTION_DIR="/function"

FROM python:3.9-slim as build-image

RUN apt-get update \
    && apt-get install -y \
        build-essential libcurl4-openssl-dev default-libmysqlclient-dev

ARG FUNCTION_DIR

RUN mkdir -p ${FUNCTION_DIR}
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt --target ${FUNCTION_DIR}
RUN pip install --no-cache-dir --target ${FUNCTION_DIR} awslambdaric

FROM python:3.9-slim

ARG FUNCTION_DIR

RUN apt-get update && apt-get install -y \
    default-mysql-client \
    alien \
    && curl -fsSLo /tmp/extension.rpm https://lambda-insights-extension.s3-ap-northeast-1.amazonaws.com/amazon_linux/lambda-insights-extension.rpm \
    && alien -i /tmp/extension.rpm \
    && apt-get remove --purge -y alien \
    && apt-get autoremove -y \
    && apt-get autoclean -y \
    && rm -rf /tmp/extension.rpm /var/lib/apt/lists/*

WORKDIR ${FUNCTION_DIR}

COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}
COPY digitraffic_figures ${FUNCTION_DIR}/digitraffic_figures
COPY app.py ${FUNCTION_DIR}

RUN python -m compileall .

ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD [ "app.handler" ]
