ALTER TABLE `key_figures` MODIFY COLUMN `from` DATE NULL;
ALTER TABLE `key_figures` MODIFY COLUMN `to` DATE NULL;
ALTER TABLE `key_figures` MODIFY COLUMN `name` VARCHAR(100) NULL;
ALTER TABLE `key_figures` MODIFY COLUMN `filter` VARCHAR(1000) NULL;
ALTER TABLE `key_figures` MODIFY COLUMN `query` VARCHAR(1000) NULL;
ALTER TABLE `key_figures` MODIFY COLUMN `value` TEXT NULL;
