version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "localhost"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    ports:
      - 3306:3306

  flyway:
    image: flyway/flyway
    command: "-url=jdbc:mysql://db/${DB_DATABASE}?allowPublicKeyRetrieval=true -password=${DB_PASSWORD} -user=${DB_USER} -connectRetries=60 migrate"
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
