export const EVENTSOURCE_VTS = "VTS";
export const EVENTSOURCE_PORTNET = "Portnet";
export const EVENTSOURCE_PORT_HANKO = "Port HKO";
export const EVENTSOURCE_TEQPLAY = "Teqplay";
export const EVENTSOURCE_SCHEDULES_VTS_CONTROL = 'SCHEDULES_VTS_CONTROLLED';
export const EVENTSOURCE_SCHEDULES_CALCULATED = 'SCHEDULES_CALCULATED';
export const EVENTSOURCE_PILOTWEB = 'Pilotweb';

export enum EventSource {
    VTS = 'VTS',
    PORTNET = 'Portnet',
    PORT_HANKO = 'Port HKO',
    TEQPLAY = 'Teqplay',
    SCHEDULES_VTS_CONTROL = 'SCHEDULES_VTS_CONTROLLED',
    SCHEDULES_CALCULATED = 'SCHEDULES_CALCULATED',
    PILOTWEB = 'Pilotweb'
}
