export const UPDATE_SWAGGER_KEYS = {
  BUCKET_NAME: "BUCKET_NAME",
  REGION: "REGION",
  APP_URL: "APP_URL",
  APP_BETA_URL: "APP_BETA_URL",
  APIGW_APPS: "APIGW_APPS",
  DIRECTORY: "DIRECTORY",
  HOST: "HOST",
  TITLE: "TITLE",
  DESCRIPTION: "DESCRIPTION",
  REMOVESECURITY: "REMOVESECURITY",
} as const;
