export const TEST_DATEX2 = `
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:situationPublication lang="fi" modelBaseVersion="3"
	xmlns="http://datex2.eu/schema/3/common"
	xmlns:ns2="http://datex2.eu/schema/3/roadTrafficData"
	xmlns:ns4="http://datex2.eu/schema/3/urbanExtensions"
	xmlns:ns3="http://datex2.eu/schema/3/situation"
	xmlns:ns6="http://datex2.eu/schema/3/facilities"
	xmlns:ns5="http://datex2.eu/schema/3/commonExtension"
	xmlns:ns8="http://datex2.eu/schema/3/locationExtension"
	xmlns:ns7="http://datex2.eu/schema/3/parking"
	xmlns:ns13="http://datex2.eu/schema/3/vms"
	xmlns:ns9="http://datex2.eu/schema/3/locationReferencing"
	xmlns:ns12="http://datex2.eu/schema/3/reroutingManagementEnhanced"
	xmlns:ns11="http://datex2.eu/schema/3/trafficManagementPlan"
	xmlns:ns10="http://datex2.eu/schema/3/faultAndStatus"
	xmlns:ns15="http://datex2.eu/schema/3/d2Payload"
	xmlns:ns14="http://datex2.eu/schema/3/energyInfrastructure">
	<publicationTime>2025-09-22T09:29:34.995Z</publicationTime>
	<publicationCreator>
		<country>FI</country>
		<nationalIdentifier>FTA</nationalIdentifier>
	</publicationCreator>
	<ns3:situation id="KRM021323">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T22:09:51.165Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM021323" version="1758233391165"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T22:09:51.165Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T22:09:51.165Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T22:09:51.165Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T22:09:51.165Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6704207.0</ns9:latitude>
						<ns9:longitude>286946.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM01K001">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-14T20:12:07.303Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM01K001" version="1758247908068"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-14T20:12:07.303Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-14T20:12:07.303Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-14T20:12:07.303Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-14T20:12:07.303Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6672259.0</ns9:latitude>
						<ns9:longitude>379389.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM011753">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T20:11:41.412Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM011753" version="1758269618959"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T20:11:41.412Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T20:11:41.412Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T20:11:41.412Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T20:11:41.412Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6759365.0</ns9:latitude>
						<ns9:longitude>429883.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM038653">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T14:11:07.360Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM038653" version="1758226376748"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T14:11:07.360Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T14:11:07.360Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T14:11:07.360Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T14:11:07.360Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6715220.0</ns9:latitude>
						<ns9:longitude>522180.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>120.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM038513">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-19T01:09:50.747Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM038513" version="1758244190747"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-19T01:09:50.747Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-19T01:09:50.747Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-19T01:09:50.747Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-19T01:09:50.747Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6717787.0</ns9:latitude>
						<ns9:longitude>527022.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>60.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM01K501">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T02:10:50.466Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM01K501" version="1758247908068"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T02:10:50.466Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T02:10:50.466Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T02:10:50.466Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T02:10:50.466Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6673062.0</ns9:latitude>
						<ns9:longitude>379488.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM038951">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T14:11:07.360Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM038951" version="1758356005192"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T14:11:07.360Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T14:11:07.360Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T14:11:07.360Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T14:11:07.360Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6718722.0</ns9:latitude>
						<ns9:longitude>545273.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM01K603">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-13T08:12:03.765Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM01K603" version="1758247908068"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-13T08:12:03.765Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-13T08:12:03.765Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-13T08:12:03.765Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-13T08:12:03.765Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6673240.0</ns9:latitude>
						<ns9:longitude>379427.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM011571">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T20:11:41.412Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM011571" version="1758226402764"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T20:11:41.412Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T20:11:41.412Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T20:11:41.412Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T20:11:41.412Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6758672.0</ns9:latitude>
						<ns9:longitude>429000.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>80.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM015812">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T20:12:55.451Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM015812" version="1758247786904"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T20:12:55.451Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T20:12:55.451Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T20:12:55.451Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T20:12:55.451Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6689696.0</ns9:latitude>
						<ns9:longitude>416897.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>80.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM01K601">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-11T14:11:39.111Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM01K601" version="1758247908068"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-11T14:11:39.111Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-11T14:11:39.111Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-11T14:11:39.111Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-11T14:11:39.111Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6673679.0</ns9:latitude>
						<ns9:longitude>378867.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM01K102">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T20:10:58.827Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM01K102" version="1758247908068"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T20:10:58.827Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T20:10:58.827Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T20:10:58.827Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T20:10:58.827Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6672562.0</ns9:latitude>
						<ns9:longitude>379418.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM011112">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T14:11:37.388Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM011112" version="1758226402764"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T14:11:37.388Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T14:11:37.388Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T14:11:37.388Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T14:11:37.388Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6758403.0</ns9:latitude>
						<ns9:longitude>422793.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>80.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM01K201">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-12T20:11:30.301Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM01K201" version="1758247908068"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-12T20:11:30.301Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-12T20:11:30.301Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-12T20:11:30.301Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-12T20:11:30.301Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6672188.0</ns9:latitude>
						<ns9:longitude>379256.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM038512">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T20:11:04.685Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM038512" version="1758226376748"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T20:11:04.685Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T20:11:04.685Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T20:11:04.685Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T20:11:04.685Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6716237.0</ns9:latitude>
						<ns9:longitude>523328.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>120.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM08053229">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T13:30:48.888Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM08053229" version="1758232856596"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T13:30:48.888Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T13:30:48.888Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T13:30:48.888Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T13:30:48.888Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6982652.0</ns9:latitude>
						<ns9:longitude>535753.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM038713">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T14:11:07.360Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM038713" version="1758442433282"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T14:11:07.360Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T14:11:07.360Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T14:11:07.360Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T14:11:07.360Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6719449.0</ns9:latitude>
						<ns9:longitude>542373.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM08053236">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T13:30:48.888Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM08053236" version="1758232856596"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T13:30:48.888Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T13:30:48.888Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T13:30:48.888Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T13:30:48.888Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6984157.0</ns9:latitude>
						<ns9:longitude>535874.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM08053226">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T13:30:48.888Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM08053226" version="1758232856596"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T13:30:48.888Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T13:30:48.888Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T13:30:48.888Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T13:30:48.888Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6981997.0</ns9:latitude>
						<ns9:longitude>535485.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
	<ns3:situation id="KRM021664">
		<ns3:overallSeverity>high</ns3:overallSeverity>
		<ns3:situationVersionTime>2025-09-18T14:10:37.306Z</ns3:situationVersionTime>
		<ns3:headerInformation>
			<confidentiality>noRestriction</confidentiality>
			<informationStatus>real</informationStatus>
		</ns3:headerInformation>
		<ns3:situationRecord xsi:type="ns3:SpeedManagement" id="KRM021664" version="1758291196246"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<ns3:situationRecordCreationTime>2025-09-18T14:10:37.306Z</ns3:situationRecordCreationTime>
			<ns3:situationRecordObservationTime>2025-09-18T14:10:37.306Z</ns3:situationRecordObservationTime>
			<ns3:situationRecordVersionTime>2025-09-18T14:10:37.306Z</ns3:situationRecordVersionTime>
			<ns3:confidentialityOverride>noRestriction</ns3:confidentialityOverride>
			<ns3:probabilityOfOccurrence>certain</ns3:probabilityOfOccurrence>
			<ns3:severity>high</ns3:severity>
			<ns3:validity>
				<validityStatus>active</validityStatus>
				<validityTimeSpecification>
					<overallStartTime>2025-09-18T14:10:37.306Z</overallStartTime>
				</validityTimeSpecification>
			</ns3:validity>
			<ns3:locationReference xsi:type="ns9:PointLocation">
				<ns9:pointByCoordinates>
					<ns9:pointCoordinates>
						<ns9:latitude>6703527.0</ns9:latitude>
						<ns9:longitude>290019.0</ns9:longitude>
					</ns9:pointCoordinates>
				</ns9:pointByCoordinates>
			</ns3:locationReference>
			<ns3:actionOrigin>internal</ns3:actionOrigin>
			<ns3:complianceOption>mandatory</ns3:complianceOption>
			<ns3:automaticallyInitiated>true</ns3:automaticallyInitiated>
			<ns3:speedManagementType>speedRestrictionInOperation</ns3:speedManagementType>
			<ns3:temporarySpeedLimit>100.0</ns3:temporarySpeedLimit>
		</ns3:situationRecord>
	</ns3:situation>
</ns3:situationPublication>`;
