export enum StatusEnvKeys {
    SECRET_ID = "SECRET_ID",
    APPS = "APPS",
    CHECK_TIMEOUT_SECONDS = "CHECK_TIMEOUT_SECONDS",
    INTERVAL_MINUTES = "INTERVAL_MINUTES",
    GITHUB_WORKFLOW_FILE = "GITHUB_WORKFLOW_FILE",
    GITHUB_BRANCH = "GITHUB_BRANCH",
    GITHUB_OWNER = "GITHUB_OWNER",
    GITHUB_REPO = "GITHUB_REPO",
    C_STATE_PAGE_URL = "C_STATE_PAGE_URL"
}
