/**
 * List of AIS navigational status codes
 */
export enum NavStatus {
  UNDER_WAY_USING_ENGINE,
  AT_ANCHOR,
  NOT_UNDER_COMMAND,
  RESTRICTED_MANEUVERABILITY,
  CONSTRAINED_BY_DRAUGHT,
  MOORED,
  AGROUND,
  FISHING,
  UNDER_WAY_SAILING,
  RESERVED,
  TOWING,
  AIS_SART,
  UNDEFINED,
}
