export const NOT_FOUND_MESSAGE = 'NOT_FOUND';
export const AUTHORIZATION_FAILED_MESSAGE = "AUTHORIZATION_FAILED";
export const ERROR_MESSAGE = 'ERROR';
export const BAD_REQUEST_MESSAGE = 'BAD REQUEST';