name: Build
on: [push]
jobs:
  build:
    if: github.event.repo.name != 'tmfg/digitraffic-cdk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install deps
        run: yarn install --frozen-lock

      - name: Derive appropriate SHAs for NX
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "master"

      - name: Compile affected
        run: yarn build:affected
