name: Build
on: [push]
jobs:
  build:
    if: github.event.repo.name != 'tmfg/digitraffic-cdk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install deps
        run: ./install_all.sh
      - name: Compile
        run: ./build_all.sh
