name: CI
on: [push, workflow_dispatch]

jobs:
  db-tests:
    if: github.repository != 'tmfg/digitraffic-cdk'
    strategy:
      fail-fast: false
      matrix:
        domain: [road, marine, rail]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout cdk repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Checkout ${{ matrix.domain }} repo
        uses: actions/checkout@v6
        with:
          repository: tmfg/digitraffic-${{ matrix.domain }}
          fetch-depth: 2
          path: digitraffic-${{ matrix.domain }}
      - name: Install Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: pipx install poetry==2.3.2
      - name: Cache pnpm store cache
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-rush-pnpm-store-${{ hashFiles('common/config/rush/repo-state.json') }}
          path: |
            common/temp/pnpm-store
      - name: Setup database for ${{ matrix.domain }}
        working-directory: digitraffic-${{ matrix.domain }}/db${{ matrix.domain }}
        run: docker compose rm db && docker compose up -d
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Update autoinstaller
        run: node common/scripts/install-run-rush.js update-autoinstaller --name rush-command-line-tools
      - name: Rush rebuild ${{ matrix.domain }}
        run: node common/scripts/install-run-rush.js rebuild --verbose --to tag:${{ matrix.domain }}
      - name: Prepare ${{ matrix.domain }}
        run: node common/scripts/install-run-rush.js ci:prepare --verbose --to tag:${{ matrix.domain }}
      - name: Run tests ${{ matrix.domain }}
        run: node common/scripts/install-run-rush.js ci:test --verbose --to tag:${{ matrix.domain }}
      - name: Teardown ${{ matrix.domain }}
        if: always()
        run: node common/scripts/install-run-rush.js ci:teardown --verbose --to tag:${{ matrix.domain }}
      - name: Publish Test Report
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        if: success() || failure() # always run even if the previous step fails
        with:
          name: Test report for ${{ matrix.domain }}
          reporter: jest-junit
          path: "${{ matrix.domain }}/**/test-results.xml"
          max-annotations: 50
          list-suites: failed
          badge-title: ${{ matrix.domain }}
      - name: Stop ${{ matrix.domain }} database containers
        if: always()
        working-directory: digitraffic-${{ matrix.domain }}/db${{ matrix.domain }}
        run: docker compose down

  other-tests:
    if: github.repository != 'tmfg/digitraffic-cdk'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        domain: [other, aviation]
    steps:
      - name: Checkout cdk repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Install Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Cache pnpm store cache
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-rush-pnpm-store-${{ hashFiles('common/config/rush/repo-state.json') }}
          path: |
            common/temp/pnpm-store
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Update autoinstaller
        run: node common/scripts/install-run-rush.js update-autoinstaller --name rush-command-line-tools
      - name: Rush rebuild ${{ matrix.domain }}
        run: node common/scripts/install-run-rush.js rebuild --verbose --to tag:${{ matrix.domain }}
      - name: Prepare ${{ matrix.domain }}
        run: node common/scripts/install-run-rush.js ci:prepare --verbose --to tag:${{ matrix.domain }}
      - name: Run tests ${{ matrix.domain }}
        run: node common/scripts/install-run-rush.js ci:test --verbose --to tag:${{ matrix.domain }}
      - name: Publish Test Report
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        if: success() || failure() # always run even if the previous step fails
        with:
          name: Test report for ${{ matrix.domain }}
          reporter: jest-junit
          path: "${{ matrix.domain }}/**/test-results.xml"
          max-annotations: 50
          list-suites: failed
          badge-title: ${{ matrix.domain }}
