name: ESLint

on: [push]

env:
  CI_DIR: "ci"

jobs:
  generate-reports:
    if: github.repository != 'tmfg/digitraffic-cdk'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: Digitraffic CI
          email: digitraffic@solita.fi
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Create eslint reports
        run: node common/scripts/install-run-rush.js ci:eslint-report

      - name: Find report files
        id: reports
        shell: sh
        run: python ${{ env.CI_DIR }}/find-reports.py

      - name: Archive reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ${{ github.ref_name }}/

  publish:
    needs: generate-reports
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Download reports
        uses: actions/download-artifact@v3
        with:
          name: reports
          path: ${{ github.ref_name }}/

      - name: Create summary
        shell: sh
        run: python ${{ env.CI_DIR }}/create-summary.py

      - name: Publish report
        uses: tmfg/digitraffic-actions@gh-pages-publish/v1
        with:
          GH_PAGES_BRANCH: gh-pages
          FILE_PATH: ${{ github.ref_name }}/
          COMMIT_MESSAGE: ESLint report in branch $CURRENT_BRANCH
          NO_SUMMARY: true
        continue-on-error: true

      # gh-pages-publish changes to gh-pages branch, which doesn't have ci scripts.
      - name: Fail on ESLint errors
        shell: python
        run: |
          import os
          import sys
          import os.path
          import json

          reports_file = os.path.join(os.environ["GITHUB_REF_NAME"], "reports.json")
          reports_created = json.loads(open(reports_file).read())
          count_errors = 0

          for report_path, _, status_line in reports_created:
              if "0 errors" in status_line:
                  print(f"No error in {report_path}. Continue")
                  continue

              print(f"Found error in {report_path}.")
              count_errors = count_errors + 1

          sys.exit(count_errors)
