name: ESLint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install ESLint
        run: yarn install --frozen-lock

      - name: Derive appropriate SHAs for NX
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "master"

      - name: Lint affected
        id: lint-affected
        run: yarn lint:affected
        continue-on-error: true

      - name: Create ESLint report
        if: steps.lint-affected.outcome != 'success'
        id: run-eslint
        run: yarn eslint . --ext .ts --format html -o ./${GITHUB_REF##*/}/eslint-report.html
        continue-on-error: true

      - name: Publish report
        if: steps.lint-affected.outcome != 'success'
        uses: tmfg/digitraffic-actions@gh-pages-publish/v1
        with:
          GH_PAGES_BRANCH: gh-pages
          FILE_PATH: ${GITHUB_REF##*/}/eslint-report.html
          COMMIT_MESSAGE: ESLint report for branch $CURRENT_BRANCH
          LINK_TEXT: ESLint report

      - name: Fail on ESLint errors
        if: steps.lint-affected.outcome != 'success'
        run: exit 1
