name: ESLint
on:
  [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      id: run-eslint
      run: yarn run eslint . --ext .js,.jsx,.ts,.tsx --format html -o ./eslint-report.html
      continue-on-error: true
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: eslint-report.html
        path: ./eslint-report.html
    - name: Fail on ESLint errors
      if: steps.run-eslint.outcome != 'success'
      run: exit 1
