name: 'Mirror repo to public'
on:
  push:
    branches:
      - master
jobs:
  Mirror-action:
    if: github.event.repo.name != 'tmfg/digitraffic-cdk'
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        uses: tmfg/digitraffic-actions@mirror/v1
        with:
          mirror-repo: git@github.com:tmfg/digitraffic-cdk.git
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
